dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - test/microbuf_tests
