dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - octave

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - test/microbuf_tests
  - cd ../test/matlab
  - octave-cli test_matlab.m
